spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres:5432/ecom_db?currentSchema=order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_service

  flyway:
    enabled: true
    default-schema: order_service
    schemas: order_service
    locations: classpath:db/migration


  mail:
    host: smtp.gmail.com
    port: 587
    username: camoudev092@gmail.com
    password: whkv lbkb ixde yztm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
