spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ecom_db?currentSchema=product_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver