spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ecom_db?currentSchema=product_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: product_service
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/ecom_ms"

profile:
  service:
    url: http://localhost:8082

review:
  service:
    url: http://localhost:8083

server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

springdoc:
  default-produces-media-type: application/json