spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/ecom_db?currentSchema=profile_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    discovery:
      enabled: true
    config:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: profile_service

server:
  port: 8082

springdoc:
  default-produces-media-type: application/json