spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres:5432/ecom_db?currentSchema=review_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: review_service

  flyway:
    enabled: true
    default-schema: review_service
    schemas: review_service
    locations: classpath:db/migration

server:
  port: 8083
